### ISSUE TITLE
Unable to select image block in edgeless mode

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1163]
Edgeless mode doesn't support block level selection, so it's inconvenient selecting and deleting the image block.

**Comment by lawvs** [comment]
Related code can found here

https://github.com/toeverything/blocksuite/blob/9a1bebc9cbd93b22c9e4c0125e7a9766ef7405b0/packages/blocks/src/__internal__/utils/selection.ts#L158-L172

**Comment by lzlme** [comment]
What is the meaning of `select` ?
Does it mean to select it by dragging? (in which case it seems to only perform a delete operation.)
Or does it make it selected by the `selection box` when you click on it, so that you can perform `caption / download / copy / delete` operations ?

If as @lawvs mentioned code, function `focusBlockByModel` from `selection.ts`, can only handle the first case.

**Comment by doodlewind** [comment]
This can be closed by #3218 since we now have block-level image popup, instead of doc mode only.

<img width="1064" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/78bd0eef-5cee-4e65-826b-2307f5f41820">
