### ISSUE TITLE
Unable to display name for multi-user cursors

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#1221]
![Image](https://user-images.githubusercontent.com/22443345/218678700-890a7590-895c-4e1b-bb07-5b6566e1ea53.png)

**Comment by doodlewind** [comment]
> @doodlewind I can't confirm whether this part is maintained in blocksuite or after

This is a UI bug in BlockSuite, transferred.

**Comment by doodlewind** [comment]
The data model of cursor names is valid, but here we have a CSS styling issue related to the quill cursor plugin (**the cursor name is hidden if the remote cursor locates at first line**). Since the quill cursor plugin absolute-positioned itself by JavaScript, it's tricky to tweak or monkey-patch it.

As an alternative, I will suggest hiding the name tag in cursor in the Downhills version. @tzhangchi @joebeijing is it acceptable?

/cc @Flrande we need to consider cursor support in Virgo, you can open new related issue for this.

**Comment by joebeijing** [comment]
Got it. @doodlewind 
If the related issue is created, please put it here.
