### ISSUE TITLE
Recognize the wrap boundary inside multi-line text

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1290]
Due to the limitation of `contenteditable`, inside a `<p>` tag, it's difficult to distinguish between the last position of first line and the start of next line. This could affects the edge case of ArrowUp support when cursor locates at the wrapped position of the line.

One approach is to use `contenteditabe` in page container level (#1272) but this may be overkill.

**Comment by doodlewind** [comment]
This affects #2805 #2834 (and more cursor related issues). And this remains after #3734 since that's still how we manage cross `contenteditable` areas. But we are open to new options.

**Comment by Flrande** [comment]
We don't need to make a distinction since we can't place the cursor at the end of the first line without causing a line break.

https://github.com/toeverything/blocksuite/assets/50035259/fd946529-6a87-4764-8a1e-9d6648f91a7c

I've reviewed issues #2834 and #4435, and I believe there are potential solutions for them. I'll allocate some time to work on it.

**Comment by doodlewind** [comment]
@Flrande I would suggest making this pending, since we have the plan migrating to one single contenteditable.
