### ISSUE TITLE
Support i18n for editor UI components

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#1296]
Currently BlockSuite seems to export hard-coded strings.

Maybe BlockSuite can integrate a custom global `t` function that can fallback to default values.

This would allow AFFiNE to add language support to BlockSuite features and functions, utilising its own definitions.

And this way it would prevent adding additional libraries or relying on AFFiNE.

**Comment by doodlewind** [comment]
This is a fair request. The difference here (between BlockSuite and AFFiNE) is that AFFiNE is using react, which has more i18n solutions out-of-the-box. But for BlockSuite, its component library (Lit) has fewer i18n support, and since these components generally have less text inside, I'm not sure about the priority of this at the moment (before we reach feature parity with pre-alpha).

But for the first step, I think it will be good to do some research and see if we can have a low-cost solution.

**Comment by lawvs** [comment]
Lit also has native Localization support, and these documents may prove to be useful.

https://lit.dev/docs/localization/overview/

**Comment by doodlewind** [comment]
Closing since we're moving internal tasks to linear, and also the i18n part would be expected to support in AFFiNE, then passing into BlockSuite via the widget and block config API.
