### ISSUE TITLE
After range delete, redundant character shows after cursor position

### ISSUE THREAD

**Issue by donaldxdonald** [toeverything/blocksuite#157]
**Description:**
At first, I pressed cmd + a to select all the text and pressed BackSpace to delete all of them. Then the next input would be triggered twice. And the extra char seems can not be deleted.

**Recording:**
![select-all](http://g.recordit.co/3LUn0aI8Ko.gif)

Then I tried commenting the code in next pic, and it worked...

![image](https://user-images.githubusercontent.com/29999387/199285431-f0adb345-af44-49b6-a718-120eb66e029a.png)

**Comment by doodlewind** [comment]
Good catch! Looks like it's an issue related to how Quill indexes the rich text instance. I think we can selectively do the `text.join()` only if the text in `lastRichText` is not empty. Which means in this range selection case (`|` for the start and end of the cursor):

```
a|bcd
efg|h
```

`deleteModels` should get `ah` instead of `a`.
