### ISSUE TITLE
Format bar not working in Safari

### ISSUE THREAD

**Issue by pengx17** [toeverything/blocksuite#1639]
When any button in the format bar is clicked, the format bar will disappear.

**Comment by doodlewind** [comment]
Hope this helps solve #881, we can test Safari by running `BROWSER=webkit pnpm test -- --debug`.

**Comment by shvixxl** [comment]
Hey! This is an old one, but this happens to me. Still only in Safari:

https://github.com/toeverything/blocksuite/assets/26658144/ac86de21-2bfa-4b61-9f47-a55198c204a2

The reason is the same: text is deselected on mouse click and format bar widget receives empty selection and decides to hide itself. https://github.com/toeverything/blocksuite/blob/3da634ddeead0a15f1c3302575378fdcf5e3ce47/packages/blocks/src/root-block/widgets/format-bar/format-bar.ts#L223

**Comment by shvixxl** [comment]
@doodlewind, uh-m, sorry, I'm not sure who I should mention. I hope I'll be able to find some time and try to fix this. Should I maybe open a new issue?
