### ISSUE TITLE
Cannot drag to select overflow contents in code block

### ISSUE THREAD

**Issue by Saul-Mirone** [toeverything/blocksuite#1685]
Originally reported in #1655 by @lawvs 

https://user-images.githubusercontent.com/18554747/224319195-a24f9cad-bcd8-4ac6-854e-13f740afc50c.mov

**Comment by doodlewind** [comment]
@adityash1 for your interest, you can try to add `console.log` in `NativeDragHandlers` to see that is the expected entry for handling our drag behavior. Basically we override the default drag behavior of the browser, computing `range` based on the cursor position (using `caretRangeFromPoint` in `handleNativeRangeDragMove`) to decide which parts should be selected.

This is the key for handling cross-block selection with multiple `contenteditable`, but things got tricky for handling more scroll types, because we have `preventDefault` it and implemented `autoScroll` for handling page level vertical scroll.

So for code block, one solution @Himself65 suggests is about adding some hard-coded logic that manually scrolls horizontally for code block, this may be acceptable. Not sure if @Flrande can tell if Virgo can easily support this feature.

**Comment by adityash1** [comment]
after merging #2076, it now automatically adds line breaks in the codeblock. Doesn't matter if we're pasting it or writing it.
which makes the wrap code utility on the tooltip pretty useless. Pasting should retain the line breaks but when we're writing, it shouldn't add line breaks automatically but should be scrolled like we're discussing here…

**Comment by doodlewind** [comment]
@adityash1 got it, we can track this behavior with new issue
