### ISSUE TITLE
Support whiteboard connector

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#1699]
Connector can be used to connect multiple shape and frames, with FigJam-like layout that automatically wiring multiple horizontal and vertical sections.

Upstream: #1289

**Comment by alt1o** [comment]
Connector data structure:
```
startElement: { id, attachPoint }
endElement: { id, attachPoint }
startPoint: [x, y]
endPoint: [x, y]
startLineCap: 'none' | 'line-arrow' | 'solid-arrow' | 'circle'
endLineCap: 'none' | 'line-arrow' | 'solid-arrow' | 'circle'
controllers: [x0, y0, x1, y1, x2, y2...]
lineType: 'elbowed' | 'straight'
```

There will be data redundancy by design. The connector's `startElement` and `endElement` are only updated when the connector changes them. If we delete startElement directly, the connector doesn't update its `startElement` property.

When the user changes `startElement` or `endElement`, we will try to find a path that is not through `startElement` and `endElement` and set all straight segments' middle points of this path as controllers.

**Comment by alt1o** [comment]
relative #1793
