### ISSUE TITLE
Do you need a Chinese translation of doc now?

### ISSUE THREAD

**Issue by lzlme** [toeverything/blocksuite#1842]

**Comment by doodlewind** [comment]
Thanks for your interest! Unlike AFFiNE, i18n support for BlockSuite documentation is not planned in the official repository at the moment, since it's still changing, and we don't have enough resources to maintain and keep them updated. However, feel free to maintain translations in your own community repository, and we'd love to add links to it!

BTW, with the blooming of AI-powered tools, I guess English documentation won't be a major blocker for most non-English speaking devs. The future is coming!
