### ISSUE TITLE
Overlapping responsibilities between Virgo Editor and Text

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#1848]
The Virgo editor has a set of methods that are similar to the `Text` API in `text-adapter.ts`, but their functionality is slightly different,  which can be confusing.

For example

```ts
function dosomething(model: BaseBlockModel) {
  const vEditor = getVirgoByModel(model);
  assertExists(vEditor, 'Editor not found');
  const text = model.text;
  assertExists(text, 'Text not found');

  // These two methods have almost the same functionality
  vEditor.deleteText({ index: 0, length: 1});
  text.delete(0,1);

  vEditor.insertText({ index: 0, length: 0 }, 'foo', { bold: true });
  text.insert('foo', 0, { bold: true });

}
```

**Comment by doodlewind** [comment]
We have 2 design goals:

1. Virgo should be usable without depending on other BlockSuite packages.
2. The BlockSuite store should wrap the `Y.Text` APIs, and it should not depend on a rich text editor to be used.

If the Virgo instance is missing (e.g., inside SSR environment), we can recommend using the `model.text.insert` API. But in browser we can generally switch to `virgo.insertText`, as long as the Virgo instance exists.

But given these 2 principles, this will result in the dually implemented methods by design. I'm not sure if it deserves merging them.

**Comment by doodlewind** [comment]
So I'd consider the current conclusion is to keep using current implementation as intended. We don't have to further refactor on this.
