### ISSUE TITLE
Select all shortcut selects whole code block instead of content inside it

### ISSUE THREAD

**Issue by adityash1** [toeverything/blocksuite#2048]
On Windows, when I press ctrl + a. it selects the code block which is generally not we want. It should select all the content inside of it.

![firefox_sTS4IWcRH0](https://user-images.githubusercontent.com/65771169/231532319-fc7a5bc0-6291-4a9f-a408-4935b087a270.gif)

**Comment by doodlewind** [comment]
I think this is mostly working as expected, since we prefer creating block-level selection over native range selection (though both are supported) on pressing `cmd-A`. I can see the issue that when pasting this selected block outside of the editor (e.g., in VSCode), the code line breaks are not kept, and this could be improved.

/cc @joebeijing

**Comment by lawvs** [comment]
Duplicated of https://github.com/toeverything/blocksuite/issues/1492

**Comment by doodlewind** [comment]
So this issue would be better closed as not planned, we can open new ones for the related clipboard issue.
