### ISSUE TITLE
Add more obvious distinctions in the Text Frame area when switching between Page and Edgeless

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2478]
When the Doc is in Page mode, when the mouse hovers over the "switch to Edgeless" button, Blocks in Edgeless that belong to different Text Frames need to visually display the boundary between the different Text Frames.

After clicking the "switch to Edgeless" button, Blocks visually assigned to different Text Frames will automatically transition to the Edgeless layout, similar to the transition effect simulated on the official website.

https://github.com/toeverything/blocksuite/assets/22443345/b2b04c7f-9c3c-4f9a-8439-c32126b4ad81

If all Blocks are under one Text Frame after switching to Edgeless, there is no need to show this type of boundary.

**Comment by doodlewind** [comment]
I think it's too aggressive to implement this at the 0.7 iteration.

**Comment by doodlewind** [comment]
Closing since the original goal will be better supported by #4159. Having this level of animation will have significant development cost and non-trivial trade off in editor architecture (so as to "merge" the UI state between two standalone editors), so this should not be in the plan of recent future.
