### ISSUE TITLE
Missing the toast containing undo button after converting database via format bar

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/blocksuite#2504]
![image](https://github.com/toeverything/blocksuite/assets/22443345/2669ee8b-8050-4ea5-b1ee-342801401ed2)
As the prototype shown

**Comment by hwangdev97** [comment]
This needs to prioritize the development of the Toast component. And linked issue：https://github.com/toeverything/AFFiNE/issues/1870

**Comment by doodlewind** [comment]
@houjoe0829 @hwangdev97 is this still required? Seems that the journey without adding toast is pretty smooth and intuitive. `cmd`-`z` after converting database works just fine.

Also, I'd not suggest adding this since the notification center is implemented in AFFiNE, using this in BlockSuite complicates how they interacts, which is also something we'd avoid if possible.

**Comment by houjoe0829** [comment]
Got it, temporarily close this requirement. If anyone has other ideas, you can reopen it at any time.
