### ISSUE TITLE
Question for slash-menu

### ISSUE THREAD

**Issue by TatisLois** [toeverything/blocksuite#2528]
Reference, I also asked in the community: https://community.affine.pro/c/questions-answers/using-the-packages-for-the-editor-and-ran-into-a-question-on-the-slash-menu

I am using the packages
`@blocksuite/blocks`
`@blocksuite/store`
`@blocksuite/editor`

To stand my own version of the editor for an app. I did not want to support all the default block schemas in `AffineSchemas` so I started to import the schema that I needed and register them myself for example

```
import { PageBlockSchema } from "@blocksuite/blocks/dist/page-block/page-model";
other schema imports ...

    workspace.register([
      ListBlockSchema,
      PageBlockSchema,
      SurfaceBlockSchema,
      FrameBlockSchema,
      ParagraphBlockSchema,
    ]);
```

My first question is if it's okay to import the individual schemas in this way, if I don't want to use every block feature.

My second question is in the `/` menu, the blocks that are not supported still show up as options, when clicked a error is throw. How can I suppress them?

Example:
<img width="573" alt="Screen Shot 2023-05-11 at 1 21 42 AM" src="https://github.com/toeverything/blocksuite/assets/11730651/114427fe-f3e7-4620-a799-dedfc56b51eb">

**Comment by Saul-Mirone** [comment]
1. It's totally fine to import the schema you need instead of import all of them. But you should notice that there're relations between different schemas. For example, the frame schema has a parent attribute and declares `affine:page` as it's parent, so you will always need to import page block if you want to use frame block. If you want to learn more details about this part, you can check the original RFC here: https://github.com/toeverything/blocksuite/issues/2002

2. We plan to support the feature that slash menu can only display buttons for imported blocks. But we haven't start the optimization. So for now, you cannot control the visibility of the buttons. But we will support that in the future.
