### ISSUE TITLE
Cursor position incorrect when hitting enter at the end of inline code

### ISSUE THREAD

**Issue by thorseraq** [toeverything/blocksuite#2791]
https://github.com/toeverything/blocksuite/assets/20554850/1f57bcd7-884b-4c2f-8277-2622186ce3aa

**Comment by smallnine9** [comment]
Unable to reproduce in version https://affine.pro/blog/whats-new-affine-0518
Could you just try the newest version or provide more info?

**Comment by doodlewind** [comment]
@smallnine9 I can still reproduce this locally (I recommend using the [BlockSuite Playground](https://blocksuite-toeverything.vercel.app/) when it comes to reproduce editor issues, which always represents the latest state in master). See this:

https://github.com/toeverything/blocksuite/assets/7312949/010789b6-2270-4e10-b2ab-f229024990ee

**Comment by smallnine9** [comment]
yes I reproduce it, seems like using cmd+z will cause this problem

**Comment by smallnine9** [comment]
finally work out why this problem happen, in fact, not just inline code case will encounter this problem:


https://github.com/toeverything/blocksuite/assets/35493996/49974f26-6da4-4739-bc9d-60bbb6ed35d5

That's because we listen 'selectionchange' in packages/blocks and packages/virgo. In blocks, we get virgo._vRange, and in virgo, we set the vRange. 
https://github.com/toeverything/blocksuite/blob/9927a75adbf11c05975324fb3a19fa48b129d86b/packages/blocks/src/page-block/default/selection-manager/selection-manager.ts#L179

https://github.com/toeverything/blocksuite/blob/9927a75adbf11c05975324fb3a19fa48b129d86b/packages/virgo/src/services/event.ts#L71
When the event is triggered, handler in blocks first execute and the range in virgo has not been set. So we will get the old and wrong _vRange.
Should we add a mechanism to manage the processing order of event listener functions defined in different modules?

**Comment by doodlewind** [comment]
The expected behavior is what #2609 wants to improve!

Regarding the Virgo issue, I think it makes sense to trigger the `selectionchange` handler inside the `blocks` package side after the `virgo` side finished necessary operations (if that's non-trivial, we can also trigger our custom event type after the virgo handler finishes, which allows more flexibility). /cc @Flrande if this can be a trivial refactor?

**Comment by smallnine9** [comment]
@doodlewind I just try using CustomEvent to trigger the logic in `blocks` package side after the `virgo` side finished _vRange updating and it seems like solving this problem.
`    document.dispatchEvent(new CustomEvent('virgorangeupdated'))
`
I think maybe that's a simple method.
I also think about adding another module to manage event listener functions in different modules, but maybe it's heavy and overengineering.

**Comment by Flrande** [comment]
> we can also trigger our custom event type after the virgo handler finishes, which allows more flexibility

I think this is a great idea! And there is another alternative solution, which is to use a slot to trigger the update logic, but this may not be well compatible with the existing code.🤔

**Comment by smallnine9** [comment]
Just commit a PR, welcome for advice :)
