### ISSUE TITLE
Last line can be ignored when moving cursor down in quote block

### ISSUE THREAD

**Issue by Innei** [toeverything/blocksuite#2834]
When moving the cursor down within a quote block, if the cursor is at the end of the second-to-last line, the last line is being ignored.

https://github.com/toeverything/blocksuite/assets/41265413/d23d4e7c-4171-4490-bf39-36826254fd34

**Comment by doodlewind** [comment]
Simpler reproduction:

https://github.com/toeverything/blocksuite/assets/7312949/10ca22fc-01aa-4cd8-b9d2-ff4b2905197b

This has something to do with https://github.com/toeverything/blocksuite/discussions/2351#discussioncomment-5754108 since we "manually" locates cursor. But unlike the regular text, pressing enter in quote block won't create a new block, but adding a soft enter in the same quote block. So the cursor behavior here can be improved. For me it's quite a interesting design in BlockSuite. Help wanted!

**Comment by water-in-stone** [comment]
Is there an imperative to rectify this issue now? If so, I will try to solve this issue.

**Comment by doodlewind** [comment]
@water-in-stone this would require a more comprehensive refactoring for `contenteditable` handling. So the advice here is to keep the current implementation, since the refactored version is supposed to be very different.
