### ISSUE TITLE
The "New Record" button at the bottom of the Database does not match the UI

### ISSUE THREAD

**Issue by joebeijing** [toeverything/blocksuite#2916]
![CleanShot 2023-05-31 at 4 09 38@2x](https://github.com/toeverything/blocksuite/assets/22443345/6d770574-5b4f-4045-a7cf-2ffc4a2f1023)
Currently, it looks like it lacks boundaries. CC @hwangdev97 

Here is the design
<img width="570" alt="img_v2_6965d7c7-bda1-4dbe-8faf-548bcbeb56dg" src="https://github.com/toeverything/blocksuite/assets/22443345/0440eb9d-5621-477a-86f6-5b81de3d571e">

**Comment by zqran** [comment]
There is no such problem in `BlockSuite`, it may be caused by the blocksuite version not being updated in Affine.

Try this: https://blocksuite-toeverything.vercel.app/?init=database.

<img width="596" alt="image" src="https://github.com/toeverything/blocksuite/assets/15389209/ac59bdf9-8d3b-44a4-afc4-fab199cadb94">
