### ISSUE TITLE
Support comment

### ISSUE THREAD

**Issue by xell** [toeverything/blocksuite#3121]
Details will be added.

**Comment by doodlewind** [comment]
@ununian thanks for your interest! We definitely recognize the importance of comments and have plans to address it (including a new tailored editor preset for it). However, due to current priorities, we might not be able to kick it off within the next few weeks. Our team would appreciate your patience and understanding as we work towards this.

**Comment by doodlewind** [comment]
Consider closed by #6302, but the overall comment feature is planned to have more progress in upcoming iterations. We'll track it with other issues.

**Comment by juzdm** [comment]
Is there any new news? affine can't use comment feature util now.

**Comment by LastSkywalkerER** [comment]
Is there any new news?

**Comment by kasvith** [comment]
Really looking forward for this...we are using outline and wanted to switch to Affine..but without comments we cant really use it

**Comment by MurzNN** [comment]
Seems comments are already implemented now, right?
