### ISSUE TITLE
The color of connector in dark mode is almost invisible.

### ISSUE THREAD

**Issue by donteatfriedrice** [toeverything/blocksuite#3130]
### What happened?

The color of connector in dark mode is almost invisible. 

https://github.com/toeverything/AFFiNE/assets/99816898/4abe192b-ea1e-46be-bc9f-387c7da5799f

It is always set as black. Could it support to keep the color when next time use connector again. For example, if last time user chose white color, next time when user want to use connector again, the color would be default set as white.

### Version

app.affine.pro

### Anything else?

Version 0.7.0-canary.14 (0.7.0-canary.14)

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by hwangdev97** [comment]
Yes, we had a long discussion about the color adaptation issue of edgeless in dark mode. But we have come to a conclusion:

1. We will **not** work on issues related to the change of color for components such as pens, shapes, and arrows in edgeless mode or related to the edgeless mode itself, **and the colors will remain the same for now**.
2. We will modify the **default colors** so that they have good readability in both dark mode and light mode.

Eventually, we will provide a feature for users to customize color selection, and users can configure the corresponding dark/light color themselves.

**Comment by donteatfriedrice** [comment]
Thanks for your reply. 
I have tried the same function in BlockSuite, it seems that BlockSuite could set the suitable default color for both light and dark mode. 
While in AFFiNE canary, when switching to dark mode, the color of connector would be dark. 

BlockSuite Playground:

https://github.com/toeverything/blocksuite/assets/99816898/8f1dbd4d-8488-43cd-8c65-6b70aeadd4b7

AFFiNE:

https://github.com/toeverything/blocksuite/assets/99816898/b423e489-fb4f-4e78-9127-65483943621a

**Comment by regischen** [comment]
So far, the blocksuite and affine-canary both provide different default colors in different themes.
As for customized default color, we wiil wait for the design.
