### ISSUE TITLE
Unstable connector starting position

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3402]
https://github.com/toeverything/blocksuite/assets/7312949/3a1aa52d-832d-4c95-acdc-e1d5a18733c6

inner feedback id: 77

**Comment by doodlewind** [comment]
This may be working as expected, tho.

**Comment by regischen** [comment]
Yeah, haha, it is a feautre.. sign.

**Comment by ShortCipher5** [comment]
The issue is not with starting in the centre - but the suggestion of a "snap" which is not actually snapped.

It is impractical to expect users to be pixel perfect with selection.

See supplied recording:

https://github.com/toeverything/blocksuite/assets/4605025/fd5604df-15e3-4401-9f3a-fac477f16316

**Comment by regischen** [comment]
maybe What the user wants is just to connector the two elements. At this time, when the element move, the connector will also look good. Otherwise, we have to adjust the connector position manually. See below:

https://github.com/toeverything/blocksuite/assets/58546692/b55b2856-1bc0-41f8-ae66-711617ab749e

If users really want to snap, When the cursor closes to element, there is blue broder circle indication, users can move cursor onit. Then it will snap.

**Comment by doodlewind** [comment]
Supported since the connected positions are stable after the position get manually adjusted.


![Image](https://github.com/toeverything/blocksuite/assets/7312949/863e6c04-0edd-4ae8-851b-55c1afe6b8df)
