### ISSUE TITLE
Support dropping a block to the children of a list item

### ISSUE THREAD

**Issue by dragonman225** [toeverything/blocksuite#3448]
I think it is convenient to use drag-and-drop to change the structure of a list, and one important action is drag-and-dropping directly to the children.

For example, in Notion (www.notion.so),

<img width="797" alt="Screenshot 2023-07-10 at 7 13 12 PM" src="https://github.com/toeverything/blocksuite/assets/25148955/148bde9f-cfb5-43ef-b307-0d3947be51af">

when I move the cursor under the text of a list item, it shows the intention of dropping to children.

In contrast, in Blocksuite,

<img width="797" alt="Screenshot 2023-07-10 at 7 11 34 PM" src="https://github.com/toeverything/blocksuite/assets/25148955/78d4e750-cb1d-41cc-9265-083f69f70126">

it always only allows me to drop as siblings.

**Comment by doodlewind** [comment]
Thanks for the feedback! I think this mainly involves some logic to restructure the blocks and prevent circular dependency. How does @lawvs think about this?

**Comment by wfnuser** [comment]
Hi there! I find this issue really interesting and seems to be a great opportunity for me to dive deeper into the project's codebase. I'd love to take on this challenge.

**Comment by wfnuser** [comment]
![chrome-capture-2023-9-1](https://github.com/toeverything/blocksuite/assets/8191686/756cf0e1-0bf1-4ba8-91d9-eebef69c4874) 
After some exploration, I've managed to implement this functionality, and it's been quite enjoyable. 

As I'm still getting acquainted with the codebase and frontend development technologies, my implementation may appear somewhat makeshift. Consequently, I'm uncertain about the optimal approach for collaboration and successfully merging this patch.

For instance, I'm uncertain whether the padding of the list tab is a fixed value or if it's defined elsewhere in the code. Additionally, I'm interested in making some changes to the API, particularly regarding the structure and enums like `DroppingType` or `DropResult`. Unfortunately, due to the lack of comprehensive documentation, I'm unsure if my proposed modifications align with your original intentions.

I'm uncertain whether my approach to implementing this function aligns with the product's standards. I've primarily followed the Logseq approach for implementation. Do you think it would be advisable for me to draft a design document before proceeding further?

I have a series of questions and I'm considering whether it might be a good idea to initiate a pull request. This way, we can address my numerous queries within the context of that PR. However, please note that my current PR might appear somewhat rudimentary, which makes me a bit hesitant.

**Comment by wfnuser** [comment]
Hi all, my holiday break has come to an end, and I'm excited to dive back into contributing to this issue within the community. Could someone please guide me on where to begin? Perhaps starting with a proposal document? I currently have a basic implementation, but there are still areas of the code that I'd like to better understand.

**Comment by doodlewind** [comment]
@wfnuser thanks for your interest in trying! Opening a draft PR with basic description should make sense, since we can provide necessary guidance and best practise about the patch.

**Comment by wfnuser** [comment]
> @wfnuser thanks for your interest in trying! Opening a draft PR with basic description should make sense, since we can provide necessary guidance and best practise about the patch.

@doodlewind  Cool. Thanks for replying. I will open a draft PR tomorrow.

**Comment by wfnuser** [comment]
@doodlewind The initial PR has been prepared. Your review would be greatly appreciated. #4961

**Comment by doodlewind** [comment]
Closed by #5276
