### ISSUE TITLE
Unable to paste plain text from code block in database

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#3488]
https://github.com/toeverything/blocksuite/assets/134897361/8c186246-e764-4fef-aa96-a61f0475bcfb

version: latest internal 
double checked with Mac and windows

**Comment by doodlewind** [comment]
Require @zqran to see if we have workaround before we land the new database clipboard transformer.

**Comment by zqran** [comment]
let me see why.

**Comment by zqran** [comment]
This is because a code block needs to be created in the database when the content of the code block is pasted in the database. 

However, the code block cannot appear in the database, so the paste fails.

https://github.com/toeverything/blocksuite/assets/15389209/30dfd12f-60b5-4e21-bd70-da7d5eba40aa
