### ISSUE TITLE
Support internal snapshot archive format

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#3654]
Currently we've supported the page level snapshot (serialized JSON block tree), but this doesn't have attachment support yet. To facilitate *lossless* content persistence support, it could be great to have such a snapshot-based format, instead of using markdown/HTML that is unable to recover content accurately.

This can be used as the backup file format at the page level (or workspace level), so that we can:

- Backup a page (or workspace) as a "clean" state.
- Easily dump an AFFiNE page into BlockSuite playground.

The implementation is supposed to be a ZIP archive with JSON and binary resources bundled. The standard of this format should be also defined.

Note that this is not going to replace the provider-based y-protocol binary format, which should be kept as the single source of truth in AFFiNE.

To be clarified:

- Do we need this format at the workspace level?
- Do we need to expose this to AFFiNE users?

/cc @houjoe0829

**Comment by jackdiy** [comment]
Thank you very much for considering this matter. The fact is, when we want users to migrate content from other document platforms, not all platforms allow content migration through online means. However, fortunately, almost all platforms have a way to export documents to MarkDown format.

However, this also means that all MarkDown documents come with a complete attachment directory, such as "assets", which is used to store images, PDFs, sounds, videos, Office documents, and so on, that users upload while writing in the document.

For example, I currently have a large online document of around 13GB that contains a large number of images and videos. I hope to migrate it to AFFiNE in bulk by exporting it to MarkDown. From a personal perspective, this compatibility work will be very helpful for users with similar migration needs. Because we can assume that almost all users have some degree of document migration needs, and starting with MarkDown seems to be the most universally applicable option.

Once again, thank you to the development team for their efforts.

**Comment by Saul-Mirone** [comment]
Closed by https://github.com/toeverything/blocksuite/pull/4614
