### ISSUE TITLE
Can't input anything when switch to page mode

### ISSUE THREAD

**Issue by youhua** [toeverything/blocksuite#3681]
1. Go to: https://blocksuite-toeverything.vercel.app/
2. Click "Switch to Page Mode"
3. Try to input anything, there is no response

https://github.com/toeverything/blocksuite/assets/1414766/4146b443-4701-428a-b9c8-42b9c68b1014

**Comment by doodlewind** [comment]
Thanks for the report! This is due to the switch of our new local-first playground (https://github.com/toeverything/blocksuite/pull/3589) and should be easy to fix. But before we land the fix, you can use https://blocksuite-toeverything.vercel.app/starter/?init (or http://localhost:5173/starter/?init) entry that works exactly as before.

**Comment by doouding** [comment]
This may due to the removing of default note block in empty preset. I'll fix it soon.
