### ISSUE TITLE
Text `foo.hello` wrongly identified as link

### ISSUE THREAD

**Issue by zanwei** [toeverything/blocksuite#3836]
### **Description**

**Now:** When inputting Heading content, if a user types '1.' and continues typing without a space, the text is displayed in link style

**Should:** Keep input style with Heading

**Notice:** The situation is repeated in all Heading styles

https://github.com/toeverything/AFFiNE/assets/40333372/ea8150d4-c14b-4008-acbc-5d70ea9b4206

### Distribution version

macOS ARM 64 (Apple Silicon)

### What browsers are you seeing the problem on if you're using web version?

Chrome

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by fourdim** [comment]
The thing is you have to add a space.
1.test is a valid link as you can see it here: https://en.wikipedia.org/wiki/.test
Many links like `release.zip` are valid domains which will redirect you to Rick Roll.
Due to technical reasons, we cannot match all the [TLD](https://en.wikipedia.org/wiki/Top-level_domain)s concerning that it will take a long time to determine whether it needs to be a link as the TLD list is too long.

See also:
https://medium.com/@bobbyrsec/the-dangers-of-googles-zip-tld-5e1e675e59a5

**Comment by zanwei** [comment]
Got it, then another issue occurs, please check the video

https://github.com/toeverything/blocksuite/assets/40333372/cb5c8dd7-99f4-4d82-bec6-085d79a53baa

**Comment by fourdim** [comment]
> Got it, then another issue occurs, please check the video
> bug.mov

Fixed in #3875.

**Comment by doodlewind** [comment]
I think the link identify condition looks too permissive, basically it turns any `[word].[word]` into link.

May relate to `autoIdentifyLink` introduced together with bookmark block, /cc @QiShaoXuan

**Comment by QiShaoXuan** [comment]
> I think the link identify condition looks too permissive, basically it turns any `[word].[word]` into link.
> 
> May relate to `autoIdentifyLink` introduced together with bookmark block, /cc @QiShaoXuan

Get, based on current user feedback, the link check should only verify whether the character ending is .com, .cn, .org, and the like.
