### ISSUE TITLE
Edgeless content position shifts on different screen size

### ISSUE THREAD

**Issue by ShortCipher5** [toeverything/blocksuite#4038]
The position of drawn content will move depending on the screen size.

Showing on smaller laptop screen:
![Image](https://user-images.githubusercontent.com/4605025/260372287-87ea0a3e-9eae-4ef9-869a-327d91dbdf1c.png)

Showing on larger external monitor:
![Image](https://user-images.githubusercontent.com/4605025/260372288-a4327d41-bbaf-4c92-b078-5de7018a9d43.png)

It can be seen that changing the screen size (or monitor) will adjust the position of drawn content.

**Comment by doouding** [comment]
Just a guess. 
Might be caused by the `devicePixelRatio`. When dragging the app window from a laptop to an external monitor, the devicePixelRatio may change if the ratios of the two monitors are different. In such cases,  the canvas should be resizied and rerendered to get the correct result.
I should have an external monitor tmr, and I can investigate further.
