### ISSUE TITLE
Unstable edgeless note height on switch between editor modes

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4166]
This happens more frequently for a page with many image-included notes.

**Comment by doodlewind** [comment]
Don't have to assign this, but would be great if @doouding can have time to take a look, since I thought you've maintained the note height related logic before.

**Comment by doouding** [comment]
I reproduce it stablely on my local enviroment. It was cause by a unnecessary `throttle` which prevent the height of note from update. Removing the throttle solve the problem, but it's still a temporary solution. Maybe we should make the height of note kind of an 'auto' value rather than maintain it manually.
