### ISSUE TITLE
IME test coverage improvement

### ISSUE THREAD

**Issue by himself65** [toeverything/blocksuite#4235]
Upstream: https://github.com/toeverything/blocksuite/pull/3854

**Comment by doodlewind** [comment]
I believe the better option is to hold this until Virgo has decent support on mobile. IME testing is actually not of our top priority, since the CJK IMEs are usable for now, and there aren't frequent breaking changes in Virgo. Also, our major paid use base for AFFiNE are European countries and America.

/cc @Flrande to see if we can have this when we need to maintain the Virgo E2E test cases.
