### ISSUE TITLE
Unable to use the "send to back" and "bring to front" buttons in edgeless

### ISSUE THREAD

**Issue by Yanxi0202** [toeverything/blocksuite#4337]

**Comment by doodlewind** [comment]
Any screen recording for reproduction?

**Comment by doodlewind** [comment]
I've verified this works as expected in playground:

https://github.com/toeverything/blocksuite/assets/7312949/18a35b67-db9b-4be8-acb8-fcf36abf2dad

Note that here you can't make the index note block higher than the shape, since the graphics content (shapes, brushes, connectors) are all placed in a canvas element that covers over all blocks, which is by design.
