### ISSUE TITLE
Support sort-by and group-by in database

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#4395]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/blocksuite/pull/4727
- [ ] https://github.com/toeverything/blocksuite/pull/4875
```

**Comment by doodlewind** [comment]
Closing as completed

**Comment by kevin61416** [comment]
This issue seems premature to close, as only the group-by feature is complete, while the **sort-by feature is still pending.**

As a forward-thinking knowledge management/note-taking app, lacking table sorting support is quite surprising.

Additionally, I suggest adding **tag-number mapping** functionality to the sort-by feature, which would greatly enhance the user experience. For example, urgent-4, high-3, medium-2, low-1. This way, the kanban can display the tag key and sort by the number value (instead of alphabetical sorting).

Overall, this is a fantastic and promising app! 😆

**Comment by agungyuliaji** [comment]
@doodlewind is there a references issue/pr regarding "sort-by" ?
