### ISSUE TITLE
Support more selection types in edgeless mode

### ISSUE THREAD

**Issue by UlyssesZh** [toeverything/blocksuite#4444]
### 1~3 main use cases of the proposed feature

Sometimes I may want to have inclusive or exclusive selection of strokes in whiteboard mode. "Inclusive" means a stroke is selected as long as any part of it is in the selected area, and "exclusive" means a stroke is selected only when the whole of it is within the selected area.
Introduce these four kinds of selections:
- Inclusive rect (already implemented);
- Exclusive rect;
- Inclusive lasso;
- Exclusive lasso.

**Comment by doodlewind** [comment]
We have rewrote the AFFiNE editor as BlockSuite (which is why this issue is transferred here), and in the new edgeless mode, the improved selection method in #3212 supports selecting elements in a hybrid way - the hollow of stroke won't be counted on hover, but if it's already selected, its selection area is counted as rect. It improves UX and hope this makes sense to you. For lasso tool support, we have #2942 in plan, but that may require some more time to land.
