### ISSUE TITLE
Copy and paste inline should not create a new line

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4545]
https://github.com/toeverything/blocksuite/assets/18554747/50ee6e14-465d-45c3-bc09-395029c9c707

**Comment by BangKk** [comment]
I'm trying to solve this issue, and I think should remove `handleBlockSplit ` code here.
Can someone  please tell me why there need split block? Thanks a lot.

https://github.com/toeverything/blocksuite/blob/52ecfd8190d777838bd2bea2464c082f13327b49/packages/blocks/src/__internal__/service/json2block.ts#L51-L57

**Comment by Flrande** [comment]
> I'm trying to solve this issue, and I think should remove handleBlockSplit  code here.
> Can someone please tell me why there need split block? Thanks a lot.

cc @fourdim @zuoxiaodong0815

**Comment by zuoxiaodong0815** [comment]
> I'm trying to solve this issue, and I think should remove `handleBlockSplit ` code here. Can someone please tell me why there need split block? Thanks a lot.
> 
> https://github.com/toeverything/blocksuite/blob/52ecfd8190d777838bd2bea2464c082f13327b49/packages/blocks/src/__internal__/service/json2block.ts#L51-L57

When the cursor is positioned in the middle of a block, the block needs to be split when pasting

**Comment by zuoxiaodong0815** [comment]
https://github.com/toeverything/blocksuite/assets/53252747/6425f800-ea11-4d6d-bb0f-ed76d67b548b

This is the split block case.

**Comment by BangKk** [comment]
> > I'm trying to solve this issue, and I think should remove `handleBlockSplit ` code here. Can someone please tell me why there need split block? Thanks a lot.
> > https://github.com/toeverything/blocksuite/blob/52ecfd8190d777838bd2bea2464c082f13327b49/packages/blocks/src/__internal__/service/json2block.ts#L51-L57
> 
> When the cursor is positioned in the middle of a block, the block needs to be split when pasting

Thank you for clarifying, it's much clearer for me. Maybe more product design clarification is needed here.

**Comment by doodlewind** [comment]
@zuoxiaodong0815 I don't think we should add `\n` in the case you provided. A part of text can just be inserted unless it's copied with `\n` at the end together. @BangKk please feel free to modify the behavior here.

**Comment by zuoxiaodong0815** [comment]
Yes, you are right @doodlewind . The issue is needed to be fixed. I just show why to split a block when focus in the middle of the block. 
The right behave when not selected whole blocks is that the selected content should be removed, and after split to tow parts, the first pasted block join in the end of the first part, the last pasted block join in the begin of the last part.
<img width="446" alt="image" src="https://github.com/toeverything/blocksuite/assets/53252747/2411c167-55a5-41ae-91fb-ac336f4b85cf">

The right behave when selected whole blocks is that the selected content does not be removed, the focus block does not be split yet, the pasted content should pasted at the behind of selected blocks.
<img width="865" alt="image" src="https://github.com/toeverything/blocksuite/assets/53252747/f3d0d2e2-3121-4f35-b48d-7131ca77d5c1">

**Comment by BangKk** [comment]
@doodlewind @zuoxiaodong0815 Thank you guys. I have found other more issues about clipboard and I'm trying to debug the code to solve them. I'm not sure whether it will be done, but later I'll submit the other issues.

**Comment by BangKk** [comment]
related issues #4619 #4620
