### ISSUE TITLE
Should not create a new line when pressing enter while using IME

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#4546]
https://github.com/toeverything/blocksuite/assets/18554747/e98a6a07-248f-46cb-82de-32994d6ca055

**Comment by doodlewind** [comment]
This is a significant regression. @lawvs do you have plan working on it (or other issues you have just opened)?

Generally we won't require issue creators to track the issues themselves, but since it's also within your scope as our team member to collaborate with @Saul-Mirone and @Flrande in doc editing, the assistance here would be appreciated.
