### ISSUE TITLE
Attachment banner icon's color doesn't change when dark-mode toggled

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#4724]
Maybe it's better to implement this by using SVG `currentColor` attribute, see #4391 

https://github.com/toeverything/blocksuite/assets/39363750/f021d58c-aa2b-4515-b38b-8f9c12371c5e

**Comment by lawvs** [comment]
Because the banner is entirely different in dark mode and light mode, it is difficult to update their display states by changing the `currentColor`.

<img width="972" alt="Screenshot 2023-09-23 at 19 53 59" src="https://github.com/toeverything/blocksuite/assets/18554747/c404d3b6-26a7-4a26-a243-1a01af6b58dc">
