### ISSUE TITLE
Image preview support

### ISSUE THREAD

**Issue by CatsJuice** [toeverything/blocksuite#4813]
I wonder if it would make more sense for the image preview to be implemented in blocksuite. Since it's currently implemented in AFFiNE, but isn't it a feature that blocksuite should have?

**Comment by doodlewind** [comment]
The envisioned best practise here is to make the implementation of image preview components standalone of the BlockSuite repo. After the extension system (proposed in #3165) landed, there should be API surface for defining custom behavior on clicking embed blocks (similar with #4399), but the corresponding components would not be maintained in this repo, since they may be using other frameworks.
