### ISSUE TITLE
Large amount of useless update data sent when new client joining

### ISSUE THREAD

**Issue by forehalo** [toeverything/blocksuite#4993]
## What happened

In collaboration scenario, I notice that whenever a page refresh happened in one tab, by which pretend to have a new client join, the existing client will receive bench of updates come from new joint client indicate that every sub pages' title were updated and the really weird thing is that they were never touched at all.

https://github.com/toeverything/blocksuite/assets/8281226/8a626630-5b26-42f4-81b0-3a28eb33ebe9

https://github.com/toeverything/blocksuite/assets/8281226/b2337913-05aa-49bc-a4a0-4f9e8e25180e

## Way to reproduce

1. two tabs in same room in playground
2. listen on the room BroadcastChannel in tab1, log the update message in console
3. reload the page in tab2

**Comment by doodlewind** [comment]
This also happens when we only use WebSocket provider (by opening https://blocksuite-toeverything.vercel.app/ with no URL suffix and click collaborate). In this mode, only WebSocket provider will be used for newly added tabs. There are also redundant messages for page B once I refresh page A:

<img width="1200" alt="image" src="https://github.com/toeverything/blocksuite/assets/7312949/e576d869-a6d7-4eca-ac46-1810bad0fc30">

(The messages here are dispatched *after* refreshing another page)
