### ISSUE TITLE
Unexpected code block scrolling behavior

### ISSUE THREAD

**Issue by forehalo** [toeverything/blocksuite#5210]
Every time I type `CMD+enter` to leave the code block and start a fresh line, the code block will scroll to very right if it's horizontally scrollable

https://github.com/toeverything/blocksuite/assets/8281226/6144da04-7daa-405f-8815-932cc506a84d

**Comment by doodlewind** [comment]
cc @Flrande to see if this is a virgo issue?

**Comment by Flrande** [comment]
May not, I will have a look.

**Comment by AyushAgrawal-A2** [comment]
@doodlewind 
Unable to reproduce (on ubuntu, pressing ctrl+enter)

https://github.com/toeverything/blocksuite/assets/54364088/97c3e34d-18bd-4316-9e9f-40094481d473

**Comment by doodlewind** [comment]
@AyushAgrawal-A2 could you please help checking out if the key binding on Linux works correctly? This operation should be bound to ctrl-enter to my knowledge.

**Comment by AyushAgrawal-A2** [comment]
@doodlewind yup, the mod-enter binding works on linux, i am able to exit code-block, list, unindent paragraphs using ctrl+enter. 
just not able to reproduce the scrolling issue mentioned above.

**Comment by doodlewind** [comment]
Thanks for the investigation! Current status:

When cursor locates at the end of a long line:

* Pressing `enter` adds a new line in the code block, then the cursor locates at the left.
* Pressing `cmd` + `enter` jumps outside of the code block, no horizontal scrolling is triggered for the code block. 

Since these work as expected, I'd consider this as not reproduced.
