### ISSUE TITLE
Partial data lost from provider

### ISSUE THREAD

**Issue by doodlewind** [toeverything/blocksuite#5323]
To reproduce:

1. Copy 1000 blocks from http://localhost:5173/starter/?init=heavy
2. Paste the blocks into http://localhost:5173/ using IndexedDB provider
3. Refresh the page, the blocks count loaded from IndexedDB would be inconsistent

https://github.com/toeverything/blocksuite/assets/7312949/b94a5dad-31b3-4d5b-b515-b964d0a45a39

This could also happen for WebSocket provider, where the `Y.encodeStateAsUpdate(page.spaceDoc)` could become `Uint8Array([0, 0])`.

**Comment by pengx17** [comment]
When copy/paste a lot of blocks into blocksuite, internally editor will use `addSerializedBlocks` to add block to the block tree one by one without using transact, it will generate a lot of `update` events that are captured by the provider and it will result in a lot of updates to IDB.

There are several factors related to this issue:
- optimize idb provider so that it will get jammed when there are lots of small updates
- investigate if it is possible to show "confirm to reload page" dialog in this case
- investigate if it is possible to wrap add block call in `addSerializedBlocks` with `transact`

**Comment by doodlewind** [comment]
Closing since this is mostly due to the slowness, which doesn't affect production since AFFiNE is using new providers.
