### ISSUE TITLE
It is possible to create a double highlight when using the handle to select a block

### ISSUE THREAD

**Issue by andyjessop** [toeverything/blocksuite#5328]
To reproduce:
1. Create a block of text.
2. Pointerdown on the handle on the left. Block is highlighted with **large** padding.
3. Pointerup on the handle. Block is now highlighted with **small** padding.
4. Pointerdown on the handle. Block is now highlighted with **small AND large** padding.

Presumably for 4, it should just be the **large** padding - i.e. the **small** padding should be deselected.

See screencast here:

https://github.com/toeverything/blocksuite/assets/1304307/b77a7954-53c8-4463-9749-8cb48a00d4b4

**Comment by doodlewind** [comment]
Thanks for the detailed description! I think I can reproduce this (in a somewhat simpler sequence) using any text block:

1. Click on the drag handle.
2. Press again on the same drag handle and don't move.

https://github.com/toeverything/blocksuite/assets/7312949/60343eae-14bf-467a-bb38-3b71e88da19c

It's pretty much an edge case, but would be great for @donteatfriedrice to see if it's a low hanging fruit for you?

**Comment by doodlewind** [comment]
We've confirmed this is actually by design, since when clicking the drag handle, there will be an overall selection box that wrap the selected nodes:

https://github.com/toeverything/blocksuite/assets/7312949/8ce7d48c-80df-4e7b-8918-df800fac5f97

And this issue is simply the edge with one block selected before clicking the drag handle.
