### ISSUE TITLE
Pasted 6000line code into editor and then it crash.​

### ISSUE THREAD

**Issue by Yipei-Operation** [toeverything/blocksuite#5837]
### What happened?

![image](https://github.com/toeverything/AFFiNE/assets/79373028/d1732ce8-10ec-439d-baf6-b8b651729e7a)
verison: linux 0.10.3 stable 
pasted 6000 line code and then it crash and can not be used
(redownload/refresh all did not work)

### Distribution version

Linux

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by Flrande** [comment]
I believe this phenomenon is due to the indexer update causing memory inflation exceeding some limitations of the browser, which then leads to crashes. I will first alleviate this issue by limiting the text length of individual blocks. Is there a way to mitigate this problem on the indexer side? @darkskygit 

<img width="978" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/f54d3be5-9139-4ee8-acde-68cc7ba2e47e">
<img width="986" alt="image" src="https://github.com/toeverything/blocksuite/assets/50035259/42410b8d-c249-45ea-b2a2-95e40e522266">

**Comment by darkskygit** [comment]
![image](https://github.com/toeverything/blocksuite/assets/25152247/b37016b0-e6b8-42b0-9b26-c4b5233b8676)

I make a memory allocation test, it looks like most of the memory allocations are caused by lit's re-rendering

**Comment by darkskygit** [comment]
![image](https://github.com/toeverything/blocksuite/assets/25152247/a7cc7405-2ed9-406d-92d5-b2d6ef90f106)
![image](https://github.com/toeverything/blocksuite/assets/25152247/abd8d2bf-45d3-4a23-8698-fdb559e914da)
![image](https://github.com/toeverything/blocksuite/assets/25152247/a1fe2551-9422-46e8-9892-377f27605060)

I tested the memory allocation of the entire life cycle in the memory tab (including memory that has been gc)
The whole process is:
1. enter the tab and wait for the memory to stabilize (about 80m)
3. start recording 4
4. create code block and paste [uniswap2_pair_070_opt_200.txt](https://github.com/toeverything/AFFiNE/files/13701195/uniswap2_pair_070_opt_200.txt)
5. wait for the memory to stabilize and go back down (about 110m)
6. 5. stop recording

**Comment by Flrande** [comment]
I updated my browser to the latest version and the abnormal increase in memory usage no longer occurs. Maybe we should update the client's Chromium version? @pengx17

**Comment by pengx17** [comment]
I tried the latest Chrome version and it seems the issue is better now. However I think the performance of our code block should still be improved. The same code I pasted in a simple code-mirror editor is much performant than ours.

Some ideas:
- indexer should not get updated so often. It seems the indexer will re-index every key-stroke, which could be debounced
- code editor should have a max height /w overflow
- code editor may need virtual rendering

**Comment by doodlewind** [comment]
I've just tested this case on windows laptop with ULV CPU (i5-1130G7 with 16GB RAM). Though this test file took about 20s to import, the content is generally responsive after being imported.

So I'd consider the crash is not reproduced, and the basic experience in this condition is supported - the perf metrics part will be tracked in #5095.
