### ISSUE TITLE
Document image upload to remote server

### ISSUE THREAD

**Issue by kyrylolvov** [toeverything/blocksuite#6294]
I'm currently test functionality of saving and then uploading snapshot of the page and got into the problem of uploading images. When uploading image and then trying to export it, it usually downloads a folder, with images in there. Is there an option to have images uploaded to S3 for example and then using URL from there?

**Comment by kyrylolvov** [comment]
@Flrande @doodlewind Is there such an option in the blocksuite library?

**Comment by doodlewind** [comment]
@kyrylolvov the current `sourceId` based blob storage can be configured and reused in this case, however the code required for customizing your remote blob data source may be a bit too verbose. One draft plan is to selectively support a `url` field in [image block](https://blocksuite.io/components/blocks/image-block.html) and [attachment block](https://blocksuite.io/components/blocks/attachment-block.html), and we'll make the priority higher since it's a common requirement.

cc @Saul-Mirone

**Comment by xiaofeiniuuu** [comment]
How can blob's image data be collaborated through sockets

**Comment by xiaofeiniuuu** [comment]
Local users can display image data through sourceId and blob, but what do users who collaborate through sockets need to do?
