### ISSUE TITLE
List block cause triple click fail to select entire paragraph

### ISSUE THREAD

**Issue by EYHN** [toeverything/blocksuite#6651]
Reproduced video from @TaylorHo

https://github.com/toeverything/blocksuite/assets/13579374/06363a95-321c-4bb4-a2f6-4a8585b3d5aa

**Comment by Flrande** [comment]
https://github.com/toeverything/blocksuite/assets/50035259/682eaefa-c980-414a-91ec-a7e0844ba81f

I can't reproduce and can you share some environmental information? 🤔

**Comment by TaylorHo** [comment]
Hey @Flrande! [Here on this another Issue](https://github.com/toeverything/AFFiNE/issues/4810#issuecomment-2026063138) are some details about how to reproduce:

> The Items where I'm trying to use the triple-click are lists (bulleted or with checkboxes). The last item of these lists is working with the triple click, really fine, but the other items (that aren't the last one) **don't have this feature working**.

The OS that I'm running into this issue is:

- macOS Sonoma 14.4.1 (23E224)
- Using Desktop application
- AFFiNE version 0.13.4 (I've first noticed this issue on 0.13.1)

If you need more details about the issue, I'm here to help you test and clarify the question! See ya.
