### ISSUE TITLE
Vertical vibration affects the recognization of native range selection

### ISSUE THREAD

**Issue by lawvs** [toeverything/blocksuite#697]
https://user-images.githubusercontent.com/18554747/212409958-98b24f86-40df-4c8d-a477-964a117940e1.mov

**Comment by himself65** [comment]
cannot reproduce on my machine

**Comment by doodlewind** [comment]
@thorseraq looks like this is related to our strategy about vertical offset?

**Comment by thorseraq** [comment]
> @thorseraq looks like this is related to our strategy about vertical offset?

yes, vertical offset is currently considered first when deciding whether the native dragging is forward or backward. The wield behavior  in the video of losing selection is because the current state is considered to be dragging backward. In this state, the endRange is where the dragging starts, the startRange is still under positioning, which is decided by position of current cursor, and can't be ahead the startRange.

A ideal way maybe first detect if the cursor in vertical direction is **text line of the start position**, and if it does, only use horizontal direction to decide whether current dragging is forward or backward. And when the cursor moves outside the current line in the vertical direction, only consider vertical offset. Maybe it can make sense

**Comment by thorseraq** [comment]
I pushed a draft behavior, how about the behavior in #783, it reuses comparePoint
