### ISSUE TITLE
⚠️🚨 Urgent Warning: Potential Scam with Clone Website block-suite.com 🚨⚠️

### ISSUE THREAD

**Issue by JacobFV** [toeverything/blocksuite#7034]
Hello,

I've noticed that there is a website (`https://block-suite.com/`) which appears to be a clone of the official Block Suite website (`https://blocksuite.io/`). This clone website could potentially confuse or mislead users, and might be involved in fraudulent activities.

Here are the details:
- Official website: [https://blocksuite.io/](https://blocksuite.io/)
- Clone website: [https://block-suite.com/](https://block-suite.com/) (potentially dangerous)

It would be great if the team could investigate this and possibly take action to protect users, such as:
1. Confirming if `https://block-suite.com/` has any affiliation with the Block Suite project.
2. Reporting the clone site to relevant authorities or taking legal steps if it is indeed a scam.
3. Alerting the community about this potential scam through official channels.

Thank you for looking into this matter to ensure the safety and integrity of the Block Suite project.

Best regards,
@JacobFV

**Comment by fourdim** [comment]
Hi, JacobFV.
https://block-suite.com/ is our legacy website which was used a couple of months ago.
It is preserved to prevent any possible dead links.
However, we still appreciate you taking the time to reach out.
CC @doodlewind to see whether we can redirect it rather than a simple CNAME.
If you have any other security concerns, please feel free to contact contact[at]toeverything.info
