### ISSUE TITLE
Unable to copy content under HTTP

### ISSUE THREAD

**Issue by Eli0x** [toeverything/blocksuite#7701]
<img width="399" alt="_20240721164603" src="https://github.com/user-attachments/assets/d8639bbc-1103-4bed-afaa-b3ec31ffb859">
<img width="660" alt="20240721164613" src="https://github.com/user-attachments/assets/aa268062-8d0d-4e4f-8484-0901bc24f1aa">

**Comment by fourdim** [comment]
Unfortunately, due to the restriction of browsers, many features like [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) only work under [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (i.e. HTTPS or localhost). I would recommend you either setup your own CA, or proxy the server to the localhost.

You can also set the flag in Chrome to disable the Secure Contexts in the trusted sources. Input the `chrome://flags/#unsafely-treat-insecure-origin-as-secure` in the Google Chrome's address bar to access this option.
