### ISSUE TITLE
Copying is not working from Affine

### ISSUE THREAD

**Issue by YourDaniel** [toeverything/blocksuite#7892]
### What happened?

I can't copy any text from Affine blocks, cmd + c is not working. In the buffer is always something that was copied before outside of Affine. Popup icon "Copy" when selecting text also doesn't work. However, copying any text not from Affine blocks, e.g. title of the page is copying normally. Only from text blocks inside notes.

Sometimes copying is working but I couldn't replicate what causes is to work or not to work.
I could reproduce it in both Chrome and Safari.

### Distribution version

macOS x64 (Intel)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Safari

### Are you self-hosting?

- [X] Yes

**Comment by fourdim** [comment]
Dup of https://github.com/toeverything/AFFiNE/issues/5610

The reason is that you are self-hosting without https.
The copy-paste require secure context to work.
Unfortunately, due to the restriction of browsers, many features like [Clipboard](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) only work under [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) (i.e. HTTPS or localhost). I would recommend you either setup your own CA, or proxy the server to the localhost.
You can set the flag in Chrome to disable the Secure Contexts in the trusted sources. Input the chrome://flags/#unsafely-treat-insecure-origin-as-secure in URL to set.
