### ISSUE TITLE
Collapse / Toggle Block Type

### ISSUE THREAD

**Issue by gotjoshua** [toeverything/blocksuite#903]
- [ ] Agree on relevance
- [ ] Agree on style
- [ ] Agree that it belongs here in [packages/blocks/src](https://github.com/toeverything/blocksuite/tree/master/packages/blocks/src)
- [ ] Agree that it is an appropriate task for a first time contributor 

| Example from Workflowy        | Example from Notion           | 
| ------------- |:-------------:| 
| ![telegram-cloud-photo-size-4-5960671904379551343-y](https://user-images.githubusercontent.com/8686454/215497247-4e0ac5aa-f98c-4143-aa9a-a2f90fcec179.jpg)    |![telegram-cloud-photo-size-4-5960671904379551396-x](https://user-images.githubusercontent.com/8686454/215497320-e8aa87ee-03de-4ed3-99ca-16cfe33e7bad.jpg) |

**Comment by doodlewind** [comment]
Hi, thanks for your feedback!

I think this is a very interesting feature, and it's also something we are going to partially covered! In our design of the DatabaseBlock (see #629), we will be able to render nest-able blocks (e.g., nested list) as sub-row in table. Folding and unfolding the row could naturally be supported when evolving the DatabaseBlock (and ListBlock).

But to my knowledge, it may be a bit hard for a first -time contributor to get things right in this feature for now, since there will also be some non-trivial modification required in the containers (e.g., page block and database block) UI and selection (deciding which block should be picked, we handle this in a more "manual" way in `selection.ts`).

So before developing this feature, I think this could be better to collect more feedback in discussion, so I'm going to convert it. Hope to see more thoughts about this!
